%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)

Camera.fx: 1304.029146
Camera.fy: 1300.360939
Camera.cx: 990.448476
Camera.cy: 515.968466

Camera.k1: -0.386216
Camera.k2: 0.140383
Camera.p1: 0.004409
Camera.p2: -0.002219
Camera.k3: 0.0

Camera.width: 1920
Camera.height: 1080

# Camera frames per second
Camera.fps: 30.0

# stereo baseline (distance between cameras in m?) times fx
Camera.bf: 57.6 # 40

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 30 # what is this?

# seen elsewhere... what is this?
#DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 1080
LEFT.width: 1920
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1304.029146, 0.000000, 990.448476, 0.000000, 1300.360939, 515.968466, 0.000000, 0.000000, 1.000000]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.998360, -0.045357, 0.034935, 0.045312, 0.998971, 0.002076, -0.034993, -0.000489, 0.999387]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [1289.951088, 0.000000, 874.958939, 0.000000, 0.000000, 1289.951088, 546.437374, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]

RIGHT.height: 1080
RIGHT.width: 1920
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.381942, 0.145040, 0.000536, 0.002452, 0.000000]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1308.636060, 0.000000, 915.116840, 0.000000, 1305.769610, 568.569179, 0.000000, 0.000000, 1.000000]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.998404, -0.028197, 0.048937, 0.028260, 0.999600, -0.000592, -0.048900, 0.001974, 0.998802]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [1289.951088, 0.000000, 874.958939, -68.012187, 0.000000, 1289.951088, 546.437374, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2400

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 4
