%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)

Camera.fx: 225.48436
Camera.fy: 299.70005
Camera.cx: 164.71275
Camera.cy: 118.01326

Camera.k1: -0.404573 
Camera.k2: 0.163958 
Camera.p1: 0.001334 
Camera.p2: -0.005042
Camera.k3: 0.0

Camera.width: 320
Camera.height: 240

# Camera frames per second
Camera.fps: 30.0

# stereo baseline (distance between cameras in m?) times fx
Camera.bf: 12.85260 # 40

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 100 # what is this?

# seen elsewhere... what is this?
#DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 320
LEFT.width: 240
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.404573, 0.163958, 0.001334, -0.005042, 0.000000]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 225.48436,    0.     ,  164.71275,
            0.     ,  299.70005,  118.01326,
            0.     ,    0.     ,    1.     ]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.95911429, -0.04577467, -0.27929279,
          0.04325362,  0.9989487 , -0.01518615,
          0.27969431,  0.00248483,  0.96008589]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 305.6735 ,    0.     ,  289.60029,    0.     ,
            0.     ,  305.6735 ,  121.06541,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]

RIGHT.height: 320
RIGHT.width: 240
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.399746, 0.164662, -0.001467, 0.001856, 0.000000]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 227.8688 ,    0.     ,  157.95209,
            0.     ,  303.09539,  118.1566 ,
            0.     ,    0.     ,    1.     ]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.97349106, -0.02827958, -0.2269701 ,
          0.03031821,  0.99952516,  0.00550008,
          0.22670678, -0.01223561,  0.9738862 ]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 305.6735 ,    0.     ,  289.60029,  -14.70807,
            0.     ,  305.6735 ,  121.06541,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2400

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
