%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)

Camera.fx: 244.429325
Camera.fy: 325.915464
Camera.cx: 165.897763
Camera.cy: 123.820184

Camera.k1: -0.41272
Camera.k2: 0.153568
Camera.p1: -0.000334
Camera.p2: -0.003140
Camera.k3: 0.0

Camera.width: 320
Camera.height: 240

# Camera frames per second
Camera.fps: 30.0

# stereo baseline (distance between cameras in m?) times fx
Camera.bf: 12.954754225 # 40

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 100 # what is this?

# seen elsewhere... what is this?
#DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 320
LEFT.width: 240
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.412729, 0.153568, -0.000334, -0.003140, 0.000000]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [244.429325, 0.000000, 165.897763, 0.000000, 325.915464, 123.820184, 0.000000, 0.000000, 1.000000]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.920705, 0.002779, 0.390251, -0.008226, 0.999891, 0.012287, -0.390174, -0.014523, 0.920627]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [343.984335, 0.000000, -82.478912, 0.000000, 0.000000, 343.984335, 132.359158, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]

RIGHT.height: 320
RIGHT.width: 240
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.373994, 0.139767, 0.000333, -0.001028, 0.000000]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [231.318831, 0.000000, 152.641652, 0.000000, 308.097601, 127.750465, 0.000000, 0.000000, 1.000000]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.918165, 0.031804, 0.394919, -0.026285, 0.999467, -0.019379, -0.395324, 0.007413, 0.918512]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [343.984335, 0.000000, -82.478912, -22.005200, 0.000000, 343.984335, 132.359158, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2400

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
