%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)

Camera.fx: 220.884778
Camera.fy: 295.457642
Camera.cx: 159.726273
Camera.cy: 121.808433

Camera.k1: -0.375914
Camera.k2: 0.134244
Camera.p1: 0.002453
Camera.p2: 0.003180
Camera.k3: 0.0

Camera.width: 320
Camera.height: 240

# Camera frames per second
Camera.fps: 10.0

# stereo baseline (distance between cameras in m?) times fx
Camera.bf: 11.7068 # 40

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 35 # what is this?

# seen elsewhere... what is this?
#DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 320
LEFT.width: 240
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.375914, 0.134244, 0.002453, 0.003180, 0.000000]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [220.884778, 0.000000, 159.726273, 0.000000, 295.457642, 121.808433, 0.000000, 0.000000, 1.000000]

LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.998000, 0.037004, 0.051257, -0.037531, 0.999252, 0.009355, -0.050873, -0.011260, 0.998642]

LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [299.438167, 0.000000, 141.389769, 0.000000, 0.000000, 299.438167, 127.613862, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]


RIGHT.height: 320
RIGHT.width: 240
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.374221, 0.133071, -0.006860, 0.003431, 0.000000]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [219.467843, 0.000000, 159.261041, 0.000000, 293.389294, 133.363559, 0.000000, 0.000000, 1.000000]

RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.999096, 0.013685, 0.040260, -0.013269, 0.999856, -0.010582, -0.040399, 0.010038, 0.999133]

RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [299.438167, 0.000000, 141.389769, -16.539961, 0.000000, 299.438167, 127.613862, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
